### ISSUE TITLE
Correct the behaviour of the composer's "delete" button in the Mailto SPA

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-mailto#13]
I'm not really sure myself what should be the behaviour of the composer's "delete" button in the Mailto SPA. Should we close the Mailto app when the button is clicked (in the Inbox SPA, the composer is closed when the button is clicked)?

**Comment by MichaelBailly** [comment]
Yes, the correct behaviour is to close the mailto app.

**Comment by tuanlc** [comment]
This should be done after resolving OpenPaaS-Suite/esn-frontend-inbox/issues#50

**Comment by tuanlc** [comment]
When you click `Delete` button, there is a toast message (grace period behind) that allows users to REOPEN the deleted composing email in a few seconds. I'm not sure how we can deal with it if we close the app.

**Comment by huy-ta** [comment]
> When you click `Delete` button, there is a toast message (grace period behind) that allows users to REOPEN the deleted composing email in a few seconds. I'm not sure how we can deal with it if we close the app?
> 
> @MichaelBailly

I think we'll wait for a few seconds before closing the app.

**Comment by MichaelBailly** [comment]
ok to wait for a few seconds
