### ISSUE TITLE
Missing the "sanitizeStylisedHtml" dependency

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-mailto#21]
#### Current behaviour

The `sanitizeStylisedHtml` dependency is missing, and there's an error thrown in the browser's console:

```
Error: [$injector:unpr] Unknown provider: sanitizeStylisedHtmlFilterProvider <- sanitizeStylisedHtmlFilter
```

#### Expected behaviour

No error related to `sanitizeStylisedHtml` is thrown.

#### Suggested solution

In `inboxComposerBodyEditorHtmlController` in `linagora.esn.unifiedinbox`, add the missing explicit dependency: `require('../../../../filters/sanitize-stylised-html-filter');`. Also add `sanitizeHtml: 'sanitize-html'` to the list of `webpack.ProvidePlugin` in `esn-frontend-mailto`.

**Comment by pbson** [comment]
Not sure why I cannot reproduce this bug. I've also tested on 2 different computer

**Comment by tuanlc** [comment]
> Not sure why I cannot reproduce this bug. I've also tested on 2 different computers

DEV platform was back. Can you check on the platform? https://dev.open-paas.org/mailto/

**Comment by pbson** [comment]
@tuanlc I've checked and the bug still remains unseen.

**Comment by huy-ta** [comment]
Since this is not irreproducible anywhere else, I'll close this issue.
