### ISSUE TITLE
Click on the email in Account > Profile tab, mail-to doesn't display the email in "to" field

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-mailto#44]
**Actual Result**

On Profile tab, click on the email, it opens mail-to box without the email in "to" textfield

![mailto](https://user-images.githubusercontent.com/69950655/92094769-008e7180-edff-11ea-9b1b-aeb6fc6412a3.png)

**Expected result**

The email that has been clicked should display in "to" text field of mail-to.

**Environment**

Desktop Ubuntu

**Comment by tuanlc** [comment]
Related PR": https://github.com/OpenPaaS-Suite/esn-frontend-mailto/pull/47
