### ISSUE TITLE
Remove popover (was: unable to interact with to field in mailto app)

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-mailto#61]
![ezgif-6-275a3a8a24c0](https://user-images.githubusercontent.com/1465817/99501083-90ae7280-297b-11eb-97af-5cb1bf24f222.gif)

Remove the popover.

**Comment by fabienmoyon** [comment]
https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/158
